# Generated by Django 2.0 on 2017-12-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='token',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
