# Generated by Django 2.0 on 2017-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(default=None, max_length=150, null=True, unique=True),
        ),
    ]
