# Generated by Django 2.0 on 2017-12-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20171227_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
