# Generated by Django 2.0 on 2018-01-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenge_solved'),
        ('teams', '0004_auto_20171227_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='solved',
            field=models.ManyToManyField(to='challenges.Challenge'),
        ),
    ]
