# Generated by Django 2.0 on 2018-01-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='correct_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wrong_flags',
            field=models.IntegerField(default=0),
        ),
    ]
