###########
# BUILDER #
###########

FROM python:3 as builder

# set work directory
WORKDIR /code

# set environment variables
ENV PYTHONUNBUFFERED 1

# lint
RUN pip install --upgrade pip
#RUN pip install flake8
COPY . /code/
#RUN flake8 --ignore=E501,F401 /code/

# install dependencies
COPY requirements.prod.txt requirements.common.txt /code/
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /code/wheels -r requirements.prod.txt -r requirements.common.txt


#########
# FINAL #
#########

# pull official base image
FROM python:3

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system app && adduser app app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/redctf
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# install dependencies
COPY --from=builder /code/wheels /wheels
COPY --from=builder /code/requirements.prod.txt /code/requirements.common.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app