FROM python:3

# set work directory
WORKDIR /code

# set environment variables
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
ADD requirements.txt /code/
RUN pip install -r requirements.txt