FROM python:3

# set work directory
WORKDIR /code

# set environment variables
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY requirements.dev.txt requirements.common.txt /code/
RUN pip install -r requirements.dev.txt -r requirements.common.txt