# Generated by Django 2.0 on 2018-01-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='solved',
        ),
    ]
