# Generated by Django 2.0 on 2018-01-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('challenges', '0004_remove_challenge_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.Category'),
        ),
    ]
