name: Prod Build

on:
  push:
    branches: 
      - master
    
  pull_request:
    branches: 
      - '**' 
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rename target compose file
      run: mv docker-compose.prod.yml docker-compose.yml
    
    - name: Rename production .env file
      run: mv ./server/.env.prod-sample ./server/.env.prod
      
    - name: Rename production .env.db file
      run: mv ./server/.env.prod.db-sample ./server/.env.prod.db
    
    - name: Build the Docker-compose file
      run: docker-compose -f "docker-compose.yml" up -d --build
